### PR TITLE
updating name of service link & add jba2.9 service links + url instances

### PR DESCRIPTION
**Pull request by lzehl**
The name in the service links should be set so that a corresponding sentence can be build the following way:
"Open _«ServiceLinkName»_ in _«ServiceName»_"

I've corrected the naming respectively.

### CODE REVIEW

**Comment by UlrikeS91** [comment]
You are trying to commit to v3 branch (which is why there are 189 changed files 😄), could you fix this first please - makes the review easier 😉

**Comment by xgui3783** [comment]
strange I can't seem to request you as the reviewer @lzehl 

I have taken over this PR muahaha 

( in seriousness, Lyuba and I spoke and I will take care of julich brain service links)

**Comment by lzehl** [comment]
@xgui3783 I've marked the PR as draft. You can switch back to ready for review when you're commits are in. I've added you as reviewer (I think because I've created the PR I cannot be assigned as reviewer). We can double check each other then :)

**Comment by xgui3783** [comment]
@lzehl the PR is ready for review

this PR includes:

- updating `name` attribute for JBA v1.18 colin 27 PM (your commit)
- fixed `-jsonld.jsonld` filenames
- added service links/URL instances for:
  - JBA v1.18 MNI152 PM
  - JBA v1.18 MNI152 MPM
  - JBA v2.9 Colin27 PM
  - JBA v2.9 Colin27 MPM
  - JBA v2.9 MNI152 PM
  - JBA v2.9 MNI152 MPM

**Comment by lzehl** [comment]
@xgui3783 thank you for all the service links. The JSONLDs are not fully correct though according to the current schema. At the moment the URL property has to link to a URL schema and cannot directly state the link. I will take care of the changes.

**Comment by xgui3783** [comment]
thanks for the update @lzehl 

My understanding was that `serviceLink.openDataIn.@id` is the link to instance of URL, as in this PR?

edit: I am currently creating service link(s) and URL(s) for bundle atlases (deep/superficial/HCP). It would be good to be able to clarify this before I submit the next PR.

**Comment by lzehl** [comment]
@xgui3783 sorry I was mistaken :see_no_evil:  I did not see that the PR review page only shows the URL instances you've created... I'll need to review locally to check all files. I'll let you know when I'm done.

**Comment by xgui3783** [comment]
@lzehl I just saw https://github.com/HumanBrainProject/openMINDS_core/pull/286 , should I modify this PR so URLs are embedded in service link?

**Comment by lzehl** [comment]
@xgui3783 that would be great (otherwise I can do it)! I wasn't sure when we are doing this structural change that is why I did not inform you in advance. The instances need then to look like this (example):

```json
{
    "@context": {
        "@vocab": "https://openminds.ebrains.eu/vocab/"
    },
    "@id": "https://openminds.ebrains.eu/instances/serviceLink/JBA-v1.18_Colin27-1998_Area-1_PM-v8.4_left",
    "@type": "https://openminds.ebrains.eu/core/ServiceLink",
    "dataLocation": {
        "@id": "https://openminds.ebrains.eu/instances/parcellationEntityVersion/JBA-v1.18_Colin27-1998_Area-1_PM-v8.4_left"
    },
    "name": "probability map",
    "openDataIn": {
        "@type": "https://openminds.ebrains.eu/core/URL",
        "URL": "https://atlases.ebrains.eu/viewer/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:7f39f7be-445b-47c0-9791-e971c0b6d992/p:minds:core:parcellationatlas:v1.0.0:94c1125b-b87e-45e4-901c-00daee7f2579/r:jubrain%20colin%20v18%20left::1z/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIx..2pi7c~.1hyh1~.3SUsT..1LSm"
    },
    "service": {
        "@id": "https://openminds.ebrains.eu/instances/service/siibraExplorer"
    }
}
```

**Comment by lzehl** [comment]
@xgui3783 the update is done. Is it correct that the PM links do not yet work?

**Comment by lzehl** [comment]
@UlrikeS91 can you double check that the format of the jsonlds is correct?. A few are enough. They are generated programmatically (if one is wrong, all will be wrong)

**Comment by UlrikeS91** [comment]
> @UlrikeS91 can you double check that the format of the jsonlds is correct?. A few are enough. They are generated programmatically (if one is wrong, all will be wrong)

Everything looks good. "openDataIn" has been changed correctly in relation to the change from linked to embeddedType. Rest also looks correct. Content seems reasonable/correct as far as I can tell, too.

**Comment by lzehl** [comment]
@UlrikeS91 :+1: thank you :slightly_smiling_face:

**Comment by lzehl** [comment]
@xgui3783 you can merge if you are happy as well.

**Pull request merged**
