### PR TITLE
Update atlasTerminology.schema.tpl.json

### PR DESCRIPTION
**Pull request by lzehl**
related to https://github.com/HumanBrainProject/openMINDS_core/pull/192

### CODE REVIEW

**Comment by lzehl** [comment]
@olinux this PR should cover the name change from the core schema FileInstance->File

**Comment by lzehl** [comment]
@UlrikeS91 feel free to double check, that I did not miss one

**Comment by lzehl** [comment]
this PR is also related to https://github.com/HumanBrainProject/openMINDS_core/issues/190

**Review by olinux — APPROVED** [review]

**Comment by lzehl** [comment]
@olinux this one became obsolete with @UlrikeS91 PR which I just merged. You can close it.

**Pull request closed without merging**
