### PR TITLE
Adding studiedSpecimen as property to brainAtlasVersion

### PR DESCRIPTION
**Pull request by lzehl**
I'm adding studied specimen as property (optional) to the brain atlas version and the common coordinate space to strengthen the information / relations around these entities.

@UlrikeS91 hope you agree with this update and can review and merge it as soon as possible?

### CODE REVIEW

**Comment by UlrikeS91** [comment]
What is the logic behind allowing it for common coordinate spaces? I agree with brain atlas versions, but for it seems a bit far-fetched for the spaces since those are quite far processed and usually rely on digital images. 

(Also, this PR is still a draft. You would need to make it into a finished one before I could merge it.)

**Comment by lzehl** [comment]
@UlrikeS91 nearly all of the coordinate spaces are based on a subject or a group of subjects that typically also are the base of the default image of a coordinate space

**Comment by lzehl** [comment]
Examples:
Colin27 is based on multiple scans of one subject.
MNI 152 is based on scans from multiple subjects
WHS is as far as I remember based on one rat brain

**Comment by UlrikeS91** [comment]
Yeah, for sure. But you are already saying it yourself - they are based on specific subjects. To me, this is closer to "input data" than it is to "studied specimen". This could in principle also apply to the brain atlas version...

**Comment by lzehl** [comment]
Yes. It also applies for BAV which corresponding change is also part of this PR.

**Comment by lzehl** [comment]
I want to have a structured way of capturing the used subjects / brains for the BAVs and the CCS instead of only being able to do so in a description which is currently the case

**Comment by lzehl** [comment]
@UlrikeS91 as discussed offline I've changed the property name to "usedSpecimen" to emphasize that the provenance to the specimen might be more distant than for normal dataset version publications.

**Review by UlrikeS91 — APPROVED** [review]

**Pull request merged**
