### PR TITLE
add abbreviation, update short & full name for BA and BAV

### PR DESCRIPTION
**Pull request by lzehl**

### CODE REVIEW

**Comment by lzehl** [comment]
@olinux ready for your review on the BA / BAV update (including instances)

**Comment by lzehl** [comment]
@olinux can you have a look at this PR? I hope this solves some of the KG Search issues.

**Review by UlrikeS91 — APPROVED** [review]

**Comment by UlrikeS91** [comment]
> @olinux can you have a look at this PR? I hope this solves some of the KG Search issues.

I took this over. Looks good and, if this is the same issue from before Christmas, this should solve the KGS issues. 

Just a question: The BrainAtlases and their corrsponding BrainAtlasVersions seem to have the same abbreviation, shortName and fullName. The only difference is the VersionIdentifier -Wouldn't it make sense to handle this similar to what we did for datasets (inheritance from BA if BAV fields are empty)?

Just an idea, if we don't want to do this (at all or just now), you can merged the PR as is :)

**Comment by lzehl** [comment]
@UlrikeS91 hey thanks for having a look at this PR. For the inheritance: inheritance rules are implemented by the KG Editor, not openMINDS. In principle these fields are never empty, because the KGE is autofilling these fields. The inheritance is therefore currently not part of the openMINDS definition. For this reason I would like to keep these values explicitly stated for the openMINDS controlled instances.

**Comment by UlrikeS91** [comment]
> @UlrikeS91 hey thanks for having a look at this PR. For the inheritance: inheritance rules are implemented by the KG Editor, not openMINDS. In principle these fields are never empty, because the KGE is autofilling these fields. The inheritance is therefore currently not part of the openMINDS definition. For this reason I would like to keep these values explicitly stated for the openMINDS controlled instances.

That makes sense :) I'll merge it then as is ;)

**Pull request merged**
