### PR TITLE
make atlas annotations embedded instances of parcellationentityversion

### PR DESCRIPTION
**Pull request by olinux**

### CODE REVIEW

**Review by lzehl — COMMENTED** [review]
The PR of today looks good.

The day before we had though  a misunderstanding . I wanted to avoid an additional lookupLabel for PEs and PEVs because the `@id` ending is the same thing and can function as a human-readable identifier already.

For the KG: could we use just the `@id` as search label for the PEs and PEVs?

**Comment by UlrikeS91** [comment]
Let fix this PR now. In an external conversation between @olinux, @lzehl and I, we discussed that the `AtlasAnnotations` need to be an embeddedTypefor tor the `ParcellationEntityVersions`. This is what this PR also prepared. BUT additionally we notice that the `AtlasAnnotation` schema has been added as a linkedType for the `core/serviceLink`. Only one of those is allowed, and because an annotation really cannot live without a PEV, we decided that the `serviceLink` should rather link to PEVs instead. 
In addition, given that AtlasAnnotation is an embeddedType, the lookUp label is also useless and needs to be removed. 

**Summary:**
SANDS/ParcellationEntityVersions --hasAnnotation--> SANDS/AtlasAnnotation (embeddedType)   
==> remains unchanged

SANDS/AtlasAnnotation --lookUpLabel--> free text 
==> needs to be removed
AND (while we are at it):
SANDS/CustomAnnotation --lookUpLabel--> free text 
==> needs to be removed (also embeddedType for "CustomAnnatomicalEntity")

core/ServiceLink --dataLocation--> SANDS/AtlasAnnotation (linkedType)
==> needs to be changed to: core/ServiceLink --dataLocation--> SANDS/ParcellationEntityVersions (linkedType)

I think this is it. But before I start implementing these changes, @olinux and @lzehl could you please confirm that this is correct? 
And if yes, @olinux, could you check that this PR for udpating the instances includes all of these point? :)

**Comment by lzehl** [comment]
@UlrikeS91 thanks for the summary. It seems to be complete from what I see. @olinux I can also do the changes in the instances if there are some left.

**Comment by lzehl** [comment]
I just checked. I think I just need to remove the lookuplabels from the atlas annotation instances.

**Comment by UlrikeS91** [comment]
This still needs to be resolved, @lzehl.

**Comment by lzehl** [comment]
@UlrikeS91 thanks for the reminder. I'll have a look at it some time in the next days.

**Comment by lzehl** [comment]
@UlrikeS91 I think this one is done. I'll just solve the conflicts and then it should be ready for merging

**Pull request merged**
