### PR TITLE
PR: add service links to WHS v1.01 v2 v3 v4

### PR DESCRIPTION
**Pull request by xgui3783**
This PR adds service links instances (linking to respective PEVs)

There are still some open questions:

- the `name` attribute for the service links, I was not too sure what is the most appropriate term to use. For Juelich Brain, we use either `maximum probability map` or `probability map`. For now, I left it as `map`
- I found some inconsistencies of the names that we have on file with those that exist in this repo, outlined below[1]. We would like to take what is in this repository as the source of truth and correct our internal names. As such, the PEV referenced as of 2b15de00179ef3b4682f0fc2ae5807b34017d5a4 is erroneous. 
- I could not find WHS3.1 on our file, and thus am not able to provide servicelinks for the PEVs.

[1] the inconsistencies follows the same structure: a tuple, with left what we have on file, and right what our best guess the correct corresponding structure in this repo

for WHS v2:

```python
exceptions = [
    ("WHSSD_v2_brainStem.jsonld", "WHSSD_v2_brainstem.jsonld"),
    ("WHSSD_v2_deeperCerebellum.jsonld", "WHSSD_v2_granuleCellLevelOfTheCerebellum.jsonld"),
    ("WHSSD_v2_anteriorCommissureIntrabulbarPart.jsonld", "WHSSD_v2_anteriorCommissure.jsonld"),
    ("WHSSD_v2_corticofugalPathways.jsonld", "WHSSD_v2_descendingCorticofugalPathways.jsonld"),
    ("WHSSD_v2_molecularCellLayerOfTheCerebellum.jsonld", "WHSSD_v2_molecularLayerOfTheCerebellum.jsonld"),
]
```

for WHS v1.01

```python
exceptions = [
    ("WHSSD_v1-01_dorsalLateralEntorhinalArea.jsonld", "WHSSD_v1-01_dorsallateralEntorhinalArea.jsonld"),
    ("WHSSD_v1-01_ventralIntermediateEntorhinalArea.jsonld","WHSSD_v1-01_ventralintermediateEntorhinalArea.jsonld"),
    ("WHSSD_v1-01_corticofugalPathways.jsonld", "WHSSD_v1-01_descendingCorticofugalPathways.jsonld"),
    ("WHSSD_v1-01_brainStem.jsonld", "WHSSD_v1-01_brainstem.jsonld"),
    ("WHSSD_v1-01_dorsalIntermediateEntorhinalArea.jsonld", "WHSSD_v1-01_dorsalintermediateEntorhinalArea.jsonld"),
]
```

### CODE REVIEW

**Comment by xgui3783** [comment]
~~Hmm, it appears the service links for v1.01, v2 and v3 are a bit faulty, I will provide a fix ASAP~~

~~v1.01 & v3 links should now be fixed (v4 should be good to begin with)~~

~~v2 links are still a bit wonky. I will have investigate further on why oO~~

the links should all be fixed (unless there's something else that I overlooked)

**Comment by UlrikeS91** [comment]
Thank you so much for making the PR @xgui3783! Sorry it took so long for me to reply, but here already some comments: 


> * the `name` attribute for the service links, I was not too sure what is the most appropriate term to use. For Juelich Brain, we use either `maximum probability map` or `probability map`. For now, I left it as `map`

'map' isn't great. Not sure if this is really true. But I think 'delineation' should be correct and "Open delineation in siibra explorer" sounds ok :) 

> * I could not find WHS3.1 on our file, and thus am not able to provide servicelinks for the PEVs.

Yes, that is correct. No worries. It's basically v3 with some name corrections. I can bring it up with Trygve and hear if he would like to update the atlases (e.g. replace v3 by v3.01). 

> * I found some inconsistencies of the names that we have on file with those that exist in this repo, outlined below[1]. We would like to take what is in this repository as the source of truth and correct our internal names. As such, the PEV referenced as of [2b15de0](https://github.com/HumanBrainProject/openMINDS_SANDS/commit/2b15de00179ef3b4682f0fc2ae5807b34017d5a4) is erroneous.
> 
> [1] the inconsistencies follows the same structure: a tuple, with left what we have on file, and right what our best guess the correct corresponding structure in this repo
> 
> for WHS v2:
> 
> ```python
> exceptions = [
>     ("WHSSD_v2_brainStem.jsonld", "WHSSD_v2_brainstem.jsonld"),
>     ("WHSSD_v2_deeperCerebellum.jsonld", "WHSSD_v2_granuleCellLevelOfTheCerebellum.jsonld"),
>     ("WHSSD_v2_anteriorCommissureIntrabulbarPart.jsonld", "WHSSD_v2_anteriorCommissure.jsonld"),
>     ("WHSSD_v2_corticofugalPathways.jsonld", "WHSSD_v2_descendingCorticofugalPathways.jsonld"),
>     ("WHSSD_v2_molecularCellLayerOfTheCerebellum.jsonld", "WHSSD_v2_molecularLayerOfTheCerebellum.jsonld"),
> ]
> ```
> 
> for WHS v1.01
> 
> ```python
> exceptions = [
>     ("WHSSD_v1-01_dorsalLateralEntorhinalArea.jsonld", "WHSSD_v1-01_dorsallateralEntorhinalArea.jsonld"),
>     ("WHSSD_v1-01_ventralIntermediateEntorhinalArea.jsonld","WHSSD_v1-01_ventralintermediateEntorhinalArea.jsonld"),
>     ("WHSSD_v1-01_corticofugalPathways.jsonld", "WHSSD_v1-01_descendingCorticofugalPathways.jsonld"),
>     ("WHSSD_v1-01_brainStem.jsonld", "WHSSD_v1-01_brainstem.jsonld"),
>     ("WHSSD_v1-01_dorsalIntermediateEntorhinalArea.jsonld", "WHSSD_v1-01_dorsalintermediateEntorhinalArea.jsonld"),
> ]
> ```

Is it bad that I am actually surprise that you only found so few errors? Either way, you're best guesses are correct. I am just surprise that you only had to create exceptions for v2 and v1.01. There are several mismatches in all versions (except for v4, I think). If you had problems with v2 and v1.01, I'm just surprise that you didn't have problems with v3.

@xgui3783, maybe you could change the serviceLink names from 'map' to 'delineation' first, before I review the PR in detail? Or would you like me to first review so that you can make all changes in one go?

**Comment by xgui3783** [comment]
Thanks for the feedback @UlrikeS91 . I will update `map` --> `delineation` ASAP, then I will ping you again for a review.

**Comment by xgui3783** [comment]
Hi @UlrikeS91 , I have pushed a commit which updated all references from `map` -> `delineation`. 

Can I ask you to take a look at the PR now?

**Comment by UlrikeS91** [comment]
> Hi @UlrikeS91 , I have pushed a commit which updated all references from `map` -> `delineation`.
> 
> Can I ask you to take a look at the PR now?

Thanks, @xgui3783. I'll review it sometime today 🙂

**Comment by xgui3783** [comment]
no rush! Thanks for looking into this!

**Review by UlrikeS91 — APPROVED** [review]
Everything looks correct. I think some of your exceptions are caused by different capitalization rules for the file names (e.g. "dorsal lateral" or "dorsal-lateral" to "dorsalLateral" and "dorsallateral" (or even treating the "-" like a space and use "doralLateral"), respectively). 

But the links for all versions are correct, so I'll merge it ☺️ 

@xgui3783 , thank you again for this!

**Comment by UlrikeS91** [comment]
FYI @olinux and @lzehl: We just merged the PR for the service links to the siibra explorer for all Waxholm PEVs. Anything I need to do or do I just wait for them to appear in the KG 😉

**Pull request merged**
