### PR TITLE
Add Aseg Atlas basic information

### PR DESCRIPTION
**Pull request by lzehl**
Described here: https://doi.org/10.1016/S0896-6273(02)00569-X

Adding for now:
+ brain atlas instance + parcellation terminology
+ parcellation entities (flat whole brain parcellation labels of Aseg Atlas; without hierarchy for now)

### CODE REVIEW

**Review by UlrikeS91 — CHANGES_REQUESTED** [review]
The instances are correct but based on the old ParcellationEntity schema. Please add "alternativeName" and "definition" (with value "null") to all of them. 

BrainAtlas looks correct, no changes required. Just a suggestion/question since you pointed to the related publication: Could that one be added as the "digitalIdentifier" for the atlas? I assume the answer is no 😉

**Comment by lzehl** [comment]
@UlrikeS91 "alternativeName" and "definition" are optional and do not have to be defined for instances if they are anyway set to null; we added those properties only in the past to remind us to fill them (in particular for controlled terms)

I don'T have an official DOI for the atlas yet no

**Comment by UlrikeS91** [comment]
> @UlrikeS91 "alternativeName" and "definition" are optional and do not have to be defined for instances if they are anyway set to null; we added those properties only in the past to remind us to fill them (in particular for controlled terms)
> 
> I don'T have an official DOI for the atlas yet no

Ok, then it should be fine to merge this. An update at some point might be nice, though.

**Review by UlrikeS91 — APPROVED** [review]

**Comment by lzehl** [comment]
@UlrikeS91 I agree. We need to see where we keep such pending updates documented. I wonder if we should really just make issues on GitHub

**Pull request merged**
