### PR TITLE
cleanup of Parcellation Entities

### PR DESCRIPTION
**Pull request by lzehl**
Includes also some content cleanup for consistency reasons (relabeling, some additional information).

### CODE REVIEW

**Comment by lzehl** [comment]
@aeidi89 all existing PEs should be updated now according to the schema changes. For consistency I've updated the lookupLabels and atids when they did not use the logic we applied now for the BA and BAVs. I've generated the PEs of each BA programmatically (meaning you don't have to review all, just a few per atlas)

**Review by skoehnen — CHANGES_REQUESTED** [review]
@lzehl It looks good so far, but I just want to make sure that the deleted files in DWMA are correct.
There are mostly modifications to existing files, but some like externalCapsule got deleted, I assume that is on purpose, I just want to make sure.

**Comment by lzehl** [comment]
@skoehnen yes that was on purpose. I went through the related data again and through siibra and realized that for all deleted DWMA entities there are actually no data available. For some reason they ended up in the label file for the maximum prop dataset of the DWM but they don't exist in data (yet). I notified the siibra team about it as well.

**Comment by skoehnen** [comment]
> @skoehnen yes that was on purpose. I went through the related data again and through siibra and realized that for all deleted DWMA entities there are actually no data available. For some reason they ended up in the label file for the maximum prop dataset of the DWM but they don't exist in data (yet). I notified the siibra team about it as well.

I just saw that you also removed the entities in the DWMA brainAtlas, I was about to merge this now :)

**Review by skoehnen — APPROVED** [review]

**Pull request merged**
