### PR TITLE
Added PEV instances for RBSC PW v6

### PR DESCRIPTION
**Pull request by ehennestad**

### CODE REVIEW

**Comment by aeidi89** [comment]
@lzehl 
Does the order of the metadata in the schema matter?
E.g.  "alternateName" is the 5th metadata in the schema, could it be placed at the end of the schema?

**Comment by lzehl** [comment]
@aeidi89 properties and value lists should be ordered alphabetically

**Comment by aeidi89** [comment]
> @aeidi89 properties and value lists should be ordered alphabetically

Thank you @lzehl 

@ehennestad could you please rearrange the properties and values so they are listed alphabetically?

**Comment by matsalan** [comment]
Hi, i have rearranged the properties and values so they are listed alphabetically, could you give me permission to push the changes?

**Comment by aeidi89** [comment]
> Hi, i have rearranged the properties and values so they are listed alphabetically, could you give me permission to push the changes?

@lzehl is this possible?

**Comment by lzehl** [comment]
@matsalan thank you for correcting the alphabetical order of the properties in the JSONLD files. However now all the JSONLDs are missing the newline character at the end of each file (POSIX standard) and the indent should be corrected to two spaces per tab. 

General question: What is RBSC PW v6 ? I would suggest to also register the respective Brain Atlas Version already with at least minimal information.

**Comment by matsalan** [comment]
It should be corrected now @lzehl.

**Comment by lzehl** [comment]
@matsalan I'm sorry but the files still miss the newline character at the end. I also still don't know the meaning for "RBSC PW v6" depending on this the lookup labels / atids may need correction as well

**Comment by lzehl** [comment]
@matsalan if you work in Python you have to add the newline character explicitely (for some reason python ignores so far the POSIX standard

**Comment by matsalan** [comment]
Is the line suppose to end with \n?

**Comment by lzehl** [comment]
@matsalan yes each json needs to end with \n

**Comment by matsalan** [comment]
Ah, but just at the bottom, not every single line right? @lzehl

**Comment by lzehl** [comment]
At the bottom. Here the way to do this via python when saving the json

``` python
with open('FILENAME.jsonld', 'a') as outfile:
    for hostDict in ....:
        json.dump(hostDict, outfile)
        outfile.write('\n') #important part rest can be different in your case
```

**Comment by matsalan** [comment]
Okay, was that done correctly? @lzehl

**Comment by lzehl** [comment]
@matsalan yepp :+1: thanks. 

Now to the naming convention:
"RBSC PW v6" apparently stands for "Rat Brain Stereotaxic Paxinos Watson version 6" (@aeidi89 thanks :slightly_smiling_face:)
I'm wondering though if the full name would not rather be "Paxinos and Watson's The Rat Brain in Stereotaxic Coordinates". And respectively the short name "Paxinos and Watson's Rat Brain" and the abbreviation "PW-RatBrain" or "PW-RBSC" or "PWRBSC". 

Unless "RBSC PW" is an official abbreviation already in use by the community.

Depending on this we should further correct the filenames, the `"@id"` and the "lookupLabel" of the PEVs

**Comment by lzehl** [comment]
@aeidi89 could we create please with this PR as well the instance for the Brain Atlas Version (with minimum metadata informations) already?

**Comment by aeidi89** [comment]
@lzehl 
Yes, we should create the Brain Atlas Version
I will have a look at doing that this week

**Comment by UlrikeS91** [comment]
I will close the PR for several reasons: 
1. instances have been combined into one repo https://github.com/openMetadataInitiative/openMINDS_instances/ and no more instances are added in the SANDS repo
2. I found errors in some of the file names of this PR 
3. I want to remove all information about annotations since this is a copyright protected atlas. I don't think we would get in trouble for stating that the annotations have been made on both hemispheres, but I just do not want to mention anything related to annotations to be on the save side.
4. All other components of the atlas are missing (BA, BAV, CCS, CCSV and PEs).

Therefore, I have started this from scratch and made a PR in the instance repo: https://github.com/openMetadataInitiative/openMINDS_instances/pull/43

**Pull request closed without merging**
