### PR TITLE
adding atlas instances for WHS version 1.01, 2, and 3

### PR DESCRIPTION
**Pull request by lzehl**
@UlrikeS91, @aeidi89 & @tgbugs here already the ParcellationEntityVersion instances for WHS version 1.01, 2, and 3
Remaining PEs and other atlas instances for WHS will follow later (today) in this PR.

### CODE REVIEW

**Comment by lzehl** [comment]
@UlrikeS91 I've corrected the ParcellationEntityVersions of WHS as well as of Brodmann (here I also corrected the already the ParcellationEntities and ParcellationTerminology(Version))

Do you want to have the AtlasAnnotations for WHS in this PR?

**Comment by tgbugs** [comment]
For reference: https://github.com/SciCrunch/NIF-Ontology/blob/parcellation/ttl/generated/parcellation/waxholm-rat-labels.ttl

**Comment by lzehl** [comment]
@tgbugs thanks for the link, but I think I do not understand how the IRI for the parcellation entity version is created from the OWLs... I only find ontology identifiers for version independent parcellation entities... could you explain?

**Comment by lzehl** [comment]
@UlrikeS91 & @aeidi89 please consider the following potential changes we can make:
+ short name of "Waxholm Space Brain Atlas of the Sprague Dawley rat" could be (A) "WHSBASD" or (B) "WHSBA-SD" or etc. (if you agree should the identifiers of the PEVs and PEs be changed accordingly?)
+ version identifiers of PEVs: currently matching the atlas version... should maybe be replaced with "v3_01" and the atID changed accordingly to "WHSBA-SD_v3_01_XX" or only changing the atID to "WHSBA-SD_v3_ XX" (instead of "WHSBA-SD_v3_ XX_v3") ? (XX would be the name of the entity in lowerCamelCase)

**Comment by lzehl** [comment]
@tgbugs we can add the ontology IDs in another PR if they are not yet available for parcellation entity versions.

**Comment by Majpuc** [comment]
Please use the abbreviated Atlas names that we are already using in our tools. It is on a private github repo, but Heidi and Ulrike have access to it: https://github.com/Neural-Systems-at-UIO/Navigator/wiki/Atlas-naming-convention
I would like to avoid problems later when we integrate the tools and the atlases to EBRAINS. Thanks!
Public copy:https://wiki.uio.no/projects/navigator3/index.php/Atlas_naming_convention

**Comment by lzehl** [comment]
@Majpuc thanks for that feedback. This should be discussed with Heidi and Trygve. The WHS ontology registrations that were already made even have another naming convention (WHSSD). Currently SANDS tries to stick to the names in the data, but there only WHS is used (which is ambiguous). this is why I extended it already. BA for Brain Atlas I'Ve added because we will also have the abbreviation WHS for only the coordinate space. So this needs to be clarified. In principle we can use SANDS to merge all of those... or do this in the ontology via synonyms. @aeidi89 & @tgbugs what do you think?

**Comment by tgbugs** [comment]
See also the fields for the atlases themselves: https://github.com/SciCrunch/NIF-Ontology/blob/parcellation/ttl/generated/parcellation-artifacts.ttl

**Comment by aeidi89** [comment]
@lzehl, should we (Trygve, Tom, you, Ulrike and I) have a call (e.g. zoom) to discuss this or is it possible to manage this in text conversation? I think I understand the issue, being that there are different naming conventions for files, atlas, etc and WHS is not specific enough (as well as the actual abbreviation for Waxholm Space and should be used for that). With history, ontology (as @tgbugs mentioned) and the file names on nitrc, I think we should stick with WHSSD (as they are used in the links from Tom) if possible. Are there any issues with using WHSSD?

**Comment by tgbugs** [comment]
WHS is too ambiguous. There is already a WHS mouse v3 as well, so WHS cannot be used by itself. Happy to hop in a call.

**Comment by lzehl** [comment]
@aeidi89 @tgbugs @Majpuc @UlrikeS91 to summarize:

We all agree: WHS stands for WaxHolm Space only which cannot be used as standalone abbreviation or name because there is more than one WHS for different species.

The ontology uses the following naming convention:
+ "Waxholm Space Sprague Dawley Terminology v1" with short name "WHSSD1" for terminology version
+ "corticofugal pathways (whssd)" for version independent parcellation entities
[I'm missing to find ontology terms for parcellation entity versions as well as atlas and atlas versions]

The naming convention of the tools that Maja brought up is:
+ "Waxholm Space atlas of the Sprague Dawley rat brain version 3" with short name "WHS Rat v3" | "WHS_Rat_v3"

The atlas data were published with the following:
+ "Waxholm Space Atlas of the Sprague Dawley Rat Brain" atlas name, with short name "WHS_SD_rat_atlas"
+ "Waxholm Space Atlas of the Sprague Dawley Rat Brain version 1.01" atlas name, with short name "WHS_SD_rat_atlas_v1.01"

The SANDS elements currently have a mixture and we can adopt to any decision. Ulrike and I even talked about introducing "synonyms" for all atlas elements so that we can list all naming conventions.

For better sorting I suggest for SANDS to define version numbers always with decimals (e.g., v2.00 or in file names v2-00) since we have version 1.01 already.

I prefer the WHS_SD_rat_atlas abbreviation, because it is precise. It defines the type of rat that was used, and specifies that we are now talking about the respective atlas. It is also easy to adopt in the other cases:
+ WHS_SD_rat for the coordinate space
+ WHS_SD_rat_atlas for the atlas
+ WHS_SD_rat_atlas_v1.01 for the atlas version
+ WHS_SD_rat_terminology for the terminology
+ WHS_SD_rat_terminology_v1.01 for the terminology version
+ WHS_SD_rat_corticofugalPathways for the parcellation entity
+ WHS_SD_rat_corticofugalPathways_v1.01 for the parcellation entity version
[this is now assuming that the version number of atlas, terminology, and parcellation entity would be the same, if this is not true 3 independent version numbers have to be introduced]

I hope we can solve this via GitHub but I'm also open for a call :)

**Comment by Majpuc** [comment]
Thank you for those precisions @aeidi89. We will adopt the convention you decide upon for future tool releases. We cannot change the naming convention for past releases. I like the idea of using synonyms in SANDS and OpenMinds, to avoid potential integration issues between files, metadata and tools.

**Comment by aeidi89** [comment]
@lzehl, I've had a brief discussion with Trygve and he wants to have a final discussion tomorrow. Ulrike or I will come back to you with Trygves feedback after tomorrow.

**Comment by lzehl** [comment]
@aeidi89 sounds good! Thanks for being so quickly involved on GitHub (@Majpuc thanks for triggering this). Any decision you make can be easily updated in the metadata via my scripts. I can push the corrections hopefully within the same day of the decision.

**Review by UlrikeS91 — APPROVED** [review]

**Pull request merged**
